name: Build and Deploy API

on:
  push:
    branches:
      - rastreamento-only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Login into docker
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          token: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Build and Push
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: arthurvieira2003/hub-logistica-frontend:latest
          no-cache: true
